---
# tasks file for kvm

- name: Expand root partition
  lvol:
    vg: ubuntu-vg
    lv: ubuntu-lv
    size: 100%
    resizefs: true

- name: Install dependencies
  ansible.builtin.apt:
    name: '{{ kvm_packages }}'
    state: present

- name: Install multipass
  community.general.snap:
    name: multipass
    classic: true
    state: present

- name: Create libvirt/kvm users
  ansible.builtin.user:
    name: '{{ kvm_user }}'
    groups: libvirt,kvm

- name: Start libvirt service
  ansible.builtin.service:
    name: libvirtd.service
    state: started
