---
# tasks file for kvm

- name: Install dependencies
  ansible.builtin.apt:
    name: '{{ kvm_packages }}'
    state: present

- name: Create ansible users
  ansible.builtin.user:
    name: '{{ kvm_user }}'
    groups: libvirt,kvm

- name: Start libvirt service
  ansible.builtin.service:
    name: libvirtd.service
    state: started
